# Generated by Django 3.2.4 on 2021-06-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Аноним')),
                ('completed', models.BooleanField(default=False)),
                ('quantity_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('questions_list', models.URLField(blank=True, null=True, unique=True)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='polls.poll')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Респондент')),
            ],
            options={
                'verbose_name': 'Прохождение опроса',
                'unique_together': {('poll', 'respondent')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_answers', polls.fields.CountAnswersField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('checkbox', models.ManyToManyField(blank=True, related_name='checkbox_answers', to='polls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.questionnaire')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.choice')),
            ],
            options={
                'unique_together': {('questionnaire', 'question')},
            },
        ),
    ]
